// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-offices.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient } from "npm:@supabase/supabase-js@^2.55.0";
function client() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_offices_default = defineTool({
  name: "list_offices",
  title: "List offices and regions",
  description: "List all regions and their area offices. Use the returned office_id / region_id values to filter facilities, payments, and permitted applications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = client();
    const [regions, offices] = await Promise.all([
      supabase.from("regions").select("id, name, code").order("name"),
      supabase.from("offices").select("id, region_id, office_name").order("office_name")
    ]);
    if (regions.error || offices.error) {
      return {
        content: [
          { type: "text", text: regions.error?.message ?? offices.error?.message ?? "Unknown error" }
        ],
        isError: true
      };
    }
    const payload = { regions: regions.data ?? [], offices: offices.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-facilities.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.55.0";
function client2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_facilities_default = defineTool2({
  name: "search_facilities",
  title: "Search facilities",
  description: "Search facility permit records. Filter by name (partial, case-insensitive), sector, district, region_id, or office_id. Returns up to `limit` rows (default 25, max 200).",
  inputSchema: {
    name: z.string().trim().min(1).optional().describe("Partial facility name match."),
    sector: z.string().trim().min(1).optional(),
    district: z.string().trim().min(1).optional(),
    region_id: z.string().uuid().optional(),
    office_id: z.string().uuid().optional(),
    limit: z.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, sector, district, region_id, office_id, limit }) => {
    let q = client2().from("facilities").select("id, name, sector, location, district, effective_date, expiry_date, region_id, office_id").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (name) q = q.ilike("name", `%${name}%`);
    if (sector) q = q.eq("sector", sector);
    if (district) q = q.ilike("district", `%${district}%`);
    if (region_id) q = q.eq("region_id", region_id);
    if (office_id) q = q.eq("office_id", office_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-payments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.55.0";
function client3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_payments_default = defineTool3({
  name: "search_payments",
  title: "Search payments",
  description: "Search payment records. Filter by payer name (partial), sector, category, region_id, office_id, or date range (payment_date between from/to, YYYY-MM-DD). Returns up to `limit` rows (default 25, max 200) plus a total_amount sum for the matched rows.",
  inputSchema: {
    name: z2.string().trim().min(1).optional(),
    sector: z2.string().trim().min(1).optional(),
    category: z2.string().trim().min(1).optional(),
    region_id: z2.string().uuid().optional(),
    office_id: z2.string().uuid().optional(),
    from: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    to: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, sector, category, region_id, office_id, from, to, limit }) => {
    let q = client3().from("payments").select("id, name, sector, category, location, amount_paid, payment_date, region_id, office_id").order("payment_date", { ascending: false }).limit(limit ?? 25);
    if (name) q = q.ilike("name", `%${name}%`);
    if (sector) q = q.eq("sector", sector);
    if (category) q = q.eq("category", category);
    if (region_id) q = q.eq("region_id", region_id);
    if (office_id) q = q.eq("office_id", office_id);
    if (from) q = q.gte("payment_date", from);
    if (to) q = q.lte("payment_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total = rows.reduce((s, r) => s + Number(r.amount_paid ?? 0), 0);
    const payload = { rows, total_amount: total, count: rows.length };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-permitted-applications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.55.0";
function client4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_permitted_applications_default = defineTool4({
  name: "search_permitted_applications",
  title: "Search permitted applications",
  description: "Search permitted-application records. Filter by facility name (partial), sector, district, region_id, or office_id. Returns up to `limit` rows (default 25, max 200).",
  inputSchema: {
    name: z3.string().trim().min(1).optional(),
    sector: z3.string().trim().min(1).optional(),
    district: z3.string().trim().min(1).optional(),
    region_id: z3.string().uuid().optional(),
    office_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, sector, district, region_id, office_id, limit }) => {
    let q = client4().from("permitted_applications").select("id, name, sector, location, district, effective_date, expiry_date, region_id, office_id").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (name) q = q.ilike("name", `%${name}%`);
    if (sector) q = q.eq("sector", sector);
    if (district) q = q.ilike("district", `%${district}%`);
    if (region_id) q = q.eq("region_id", region_id);
    if (office_id) q = q.eq("office_id", office_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "facility-finder-mcp",
  title: "Facility Finder MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Facility Finder database. Call `list_offices` first to discover region_id and office_id values, then use them to filter `search_facilities`, `search_payments`, and `search_permitted_applications`. This server is public \u2014 all data returned is accessible without authentication.",
  tools: [list_offices_default, search_facilities_default, search_payments_default, search_permitted_applications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
