CREATE TABLE public.permitted_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  sector text,
  location text,
  district text,
  effective_date text,
  expiry_date text,
  file_location_id text,
  region_id uuid REFERENCES public.regions(id),
  office_id uuid REFERENCES public.offices(id)
);

ALTER TABLE public.permitted_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read permitted_applications" ON public.permitted_applications FOR SELECT USING (true);
CREATE POLICY "Allow inserts on permitted_applications" ON public.permitted_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow updates on permitted_applications" ON public.permitted_applications FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow deletes on permitted_applications" ON public.permitted_applications FOR DELETE USING (true);